"""initial schema

Revision ID: 18bcab74900e
Revises: 
Create Date: 2026-09-13 06:51:43.906876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bcab74900e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('full_width', sa.Boolean(), nullable=False),
    sa.Column('columns', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('sheet_name', sa.String(length=120), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('inserted', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lookup_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name_fa', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allows_multiple', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lookup_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookup_categories_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=30), nullable=False),
    sa.Column('model_attr', sa.String(length=80), nullable=True),
    sa.Column('lookup_category', sa.String(length=60), nullable=True),
    sa.Column('placeholder', sa.String(length=200), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('default_value', sa.String(length=200), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('allow_other', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('col_span', sa.Integer(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('step', sa.String(length=20), nullable=True),
    sa.Column('show_in_table', sa.Boolean(), nullable=False),
    sa.Column('table_order', sa.Integer(), nullable=False),
    sa.Column('export_header', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['form_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_fields_field_name'), ['field_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_form_fields_section_id'), ['section_id'], unique=False)

    op.create_table('lookup_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_adhoc', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['lookup_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'value', name='uq_lookup_category_value')
    )
    with op.batch_alter_table('lookup_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookup_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lookup_items_is_active'), ['is_active'], unique=False)

    op.create_table('form_field_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_field_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_field_options_field_id'), ['field_id'], unique=False)

    op.create_table('lookup_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['lookup_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['lookup_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'alias', name='uq_lookup_alias')
    )
    with op.batch_alter_table('lookup_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookup_aliases_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lookup_aliases_item_id'), ['item_id'], unique=False)

    op.create_table('wells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['lookup_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wells', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wells_center_id'), ['center_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wells_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_wells_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_wells_name'), ['name'], unique=True)

    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('j_year', sa.Integer(), nullable=True),
    sa.Column('j_month', sa.Integer(), nullable=True),
    sa.Column('j_day', sa.Integer(), nullable=True),
    sa.Column('op_date', sa.Date(), nullable=True),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('well_name_raw', sa.String(length=200), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('pm_id', sa.Integer(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('failure_other', sa.Text(), nullable=True),
    sa.Column('motor_prev_id', sa.Integer(), nullable=True),
    sa.Column('motor_curr_id', sa.Integer(), nullable=True),
    sa.Column('motor_plaque', sa.String(length=80), nullable=True),
    sa.Column('motor_maker_id', sa.Integer(), nullable=True),
    sa.Column('motor_condition_id', sa.Integer(), nullable=True),
    sa.Column('motor_rewind_id', sa.Integer(), nullable=True),
    sa.Column('pump_prev_id', sa.Integer(), nullable=True),
    sa.Column('pump_prev_stages', sa.Integer(), nullable=True),
    sa.Column('pump_prev_raw', sa.String(length=80), nullable=True),
    sa.Column('pump_curr_id', sa.Integer(), nullable=True),
    sa.Column('pump_stages', sa.Integer(), nullable=True),
    sa.Column('pump_plaque', sa.String(length=80), nullable=True),
    sa.Column('pump_maker_id', sa.Integer(), nullable=True),
    sa.Column('pump_condition_id', sa.Integer(), nullable=True),
    sa.Column('type_change_id', sa.Integer(), nullable=True),
    sa.Column('prev_install_date', sa.Date(), nullable=True),
    sa.Column('prev_install_date_raw', sa.String(length=40), nullable=True),
    sa.Column('well_depth', sa.Float(), nullable=True),
    sa.Column('prev_install_depth', sa.Float(), nullable=True),
    sa.Column('curr_install_depth', sa.Float(), nullable=True),
    sa.Column('static_level', sa.Float(), nullable=True),
    sa.Column('dynamic_level', sa.Float(), nullable=True),
    sa.Column('path_loss', sa.Float(), nullable=True),
    sa.Column('network_pressure', sa.Float(), nullable=True),
    sa.Column('total_head', sa.Float(), nullable=True),
    sa.Column('design_flow', sa.Float(), nullable=True),
    sa.Column('pipe_diameter_id', sa.Integer(), nullable=True),
    sa.Column('cable_type_change_id', sa.Integer(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('test_date_raw', sa.String(length=40), nullable=True),
    sa.Column('test_pressure', sa.Float(), nullable=True),
    sa.Column('test_flow', sa.Float(), nullable=True),
    sa.Column('cable_size_change_id', sa.Integer(), nullable=True),
    sa.Column('cable_well', sa.String(length=200), nullable=True),
    sa.Column('starter_id', sa.Integer(), nullable=True),
    sa.Column('cable_size_id', sa.Integer(), nullable=True),
    sa.Column('pull_year', sa.Integer(), nullable=True),
    sa.Column('pull_month', sa.Integer(), nullable=True),
    sa.Column('old_install_year', sa.Integer(), nullable=True),
    sa.Column('old_install_month', sa.Integer(), nullable=True),
    sa.Column('working_months', sa.Integer(), nullable=True),
    sa.Column('young_wells', sa.Integer(), nullable=True),
    sa.Column('workshop_note', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('install_supervisor', sa.String(length=120), nullable=True),
    sa.Column('flow_after_install', sa.Float(), nullable=True),
    sa.Column('flow_before_pull', sa.Float(), nullable=True),
    sa.Column('flow_before_pull_date', sa.String(length=40), nullable=True),
    sa.Column('flow_after_install_date', sa.String(length=40), nullable=True),
    sa.Column('casing_length', sa.Float(), nullable=True),
    sa.Column('casing_pulled_diameter', sa.String(length=40), nullable=True),
    sa.Column('casing_repair_count', sa.Integer(), nullable=True),
    sa.Column('casing_material', sa.String(length=80), nullable=True),
    sa.Column('casing_diameter', sa.String(length=40), nullable=True),
    sa.Column('documents_ref', sa.String(length=200), nullable=True),
    sa.Column('reported_to_finance', sa.Boolean(), nullable=True),
    sa.Column('source_sheet', sa.String(length=60), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cable_size_change_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['cable_size_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['cable_type_change_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['motor_condition_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['motor_curr_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['motor_maker_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['motor_prev_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['motor_rewind_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['pipe_diameter_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['pm_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['pump_condition_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['pump_curr_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['pump_maker_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['pump_prev_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['starter_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['type_change_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_records_cable_size_change_id'), ['cable_size_change_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_cable_size_id'), ['cable_size_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_cable_type_change_id'), ['cable_type_change_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_center_id'), ['center_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_contractor_id'), ['contractor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_executor_id'), ['executor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_j_month'), ['j_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_j_year'), ['j_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_motor_condition_id'), ['motor_condition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_motor_curr_id'), ['motor_curr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_motor_maker_id'), ['motor_maker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_motor_prev_id'), ['motor_prev_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_motor_rewind_id'), ['motor_rewind_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_op_date'), ['op_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_operation_id'), ['operation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_pipe_diameter_id'), ['pipe_diameter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_pm_id'), ['pm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_pull_year'), ['pull_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_pump_condition_id'), ['pump_condition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_pump_curr_id'), ['pump_curr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_pump_maker_id'), ['pump_maker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_pump_prev_id'), ['pump_prev_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_starter_id'), ['starter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_type_change_id'), ['type_change_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_well_id'), ['well_id'], unique=False)

    op.create_table('well_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', name='uq_well_alias')
    )
    with op.batch_alter_table('well_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_well_aliases_well_id'), ['well_id'], unique=False)

    op.create_table('pump_curve_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('head', sa.Float(), nullable=True),
    sa.Column('table_flow', sa.Float(), nullable=True),
    sa.Column('initial_flow', sa.Float(), nullable=True),
    sa.Column('return_flow', sa.Float(), nullable=True),
    sa.Column('months_in_service', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pump_curve_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pump_curve_points_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pump_curve_points_well_id'), ['well_id'], unique=False)

    op.create_table('record_dynamic_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'field_id', name='uq_record_field')
    )
    with op.batch_alter_table('record_dynamic_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_dynamic_values_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_dynamic_values_record_id'), ['record_id'], unique=False)

    op.create_table('record_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=60), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['lookup_items.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('record_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_tags_category_code'), ['category_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_tags_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_tags_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_tags_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_tags_value'))
        batch_op.drop_index(batch_op.f('ix_record_tags_record_id'))
        batch_op.drop_index(batch_op.f('ix_record_tags_item_id'))
        batch_op.drop_index(batch_op.f('ix_record_tags_category_code'))

    op.drop_table('record_tags')
    with op.batch_alter_table('record_dynamic_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_dynamic_values_record_id'))
        batch_op.drop_index(batch_op.f('ix_record_dynamic_values_field_id'))

    op.drop_table('record_dynamic_values')
    with op.batch_alter_table('pump_curve_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pump_curve_points_well_id'))
        batch_op.drop_index(batch_op.f('ix_pump_curve_points_record_id'))

    op.drop_table('pump_curve_points')
    with op.batch_alter_table('well_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_well_aliases_well_id'))

    op.drop_table('well_aliases')
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_records_well_id'))
        batch_op.drop_index(batch_op.f('ix_records_type_change_id'))
        batch_op.drop_index(batch_op.f('ix_records_starter_id'))
        batch_op.drop_index(batch_op.f('ix_records_shift_id'))
        batch_op.drop_index(batch_op.f('ix_records_pump_prev_id'))
        batch_op.drop_index(batch_op.f('ix_records_pump_maker_id'))
        batch_op.drop_index(batch_op.f('ix_records_pump_curr_id'))
        batch_op.drop_index(batch_op.f('ix_records_pump_condition_id'))
        batch_op.drop_index(batch_op.f('ix_records_pull_year'))
        batch_op.drop_index(batch_op.f('ix_records_pm_id'))
        batch_op.drop_index(batch_op.f('ix_records_pipe_diameter_id'))
        batch_op.drop_index(batch_op.f('ix_records_operation_id'))
        batch_op.drop_index(batch_op.f('ix_records_op_date'))
        batch_op.drop_index(batch_op.f('ix_records_motor_rewind_id'))
        batch_op.drop_index(batch_op.f('ix_records_motor_prev_id'))
        batch_op.drop_index(batch_op.f('ix_records_motor_maker_id'))
        batch_op.drop_index(batch_op.f('ix_records_motor_curr_id'))
        batch_op.drop_index(batch_op.f('ix_records_motor_condition_id'))
        batch_op.drop_index(batch_op.f('ix_records_j_year'))
        batch_op.drop_index(batch_op.f('ix_records_j_month'))
        batch_op.drop_index(batch_op.f('ix_records_is_active'))
        batch_op.drop_index(batch_op.f('ix_records_import_batch_id'))
        batch_op.drop_index(batch_op.f('ix_records_executor_id'))
        batch_op.drop_index(batch_op.f('ix_records_contractor_id'))
        batch_op.drop_index(batch_op.f('ix_records_center_id'))
        batch_op.drop_index(batch_op.f('ix_records_cable_type_change_id'))
        batch_op.drop_index(batch_op.f('ix_records_cable_size_id'))
        batch_op.drop_index(batch_op.f('ix_records_cable_size_change_id'))

    op.drop_table('records')
    with op.batch_alter_table('wells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wells_name'))
        batch_op.drop_index(batch_op.f('ix_wells_is_active'))
        batch_op.drop_index(batch_op.f('ix_wells_code'))
        batch_op.drop_index(batch_op.f('ix_wells_center_id'))

    op.drop_table('wells')
    with op.batch_alter_table('lookup_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookup_aliases_item_id'))
        batch_op.drop_index(batch_op.f('ix_lookup_aliases_category_id'))

    op.drop_table('lookup_aliases')
    with op.batch_alter_table('form_field_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_field_options_field_id'))

    op.drop_table('form_field_options')
    with op.batch_alter_table('lookup_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookup_items_is_active'))
        batch_op.drop_index(batch_op.f('ix_lookup_items_category_id'))

    op.drop_table('lookup_items')
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_fields_section_id'))
        batch_op.drop_index(batch_op.f('ix_form_fields_field_name'))

    op.drop_table('form_fields')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('users')
    with op.batch_alter_table('lookup_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookup_categories_code'))

    op.drop_table('lookup_categories')
    op.drop_table('import_batches')
    op.drop_table('form_sections')
    # ### end Alembic commands ###
