"""PM code and class on wells, users, sessions

Revision ID: 850ea3df5f9f
Revises: 18bcab74900e
Create Date: 2026-09-13 14:23:14.227459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850ea3df5f9f'
down_revision = '18bcab74900e'
branch_labels = None
depends_on = None


# Deterministic names for SQLite's anonymous foreign keys, so batch mode can
# address them. Must match how the constraint was originally emitted.
FK_NAMING = {
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('father_name', sa.String(length=80), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('personnel_code', sa.String(length=40), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('permissions_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=60), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_users_national_id'), ['national_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_users_personnel_code'), ['personnel_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_users_username'), ['username'], unique=True)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('logout_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('end_reason', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_login_at'), ['login_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    # SQLite writes these foreign keys without a name, and batch mode cannot
    # drop an unnamed constraint. A naming convention gives the existing
    # constraint a deterministic name so it can be dropped and re-pointed at
    # the new app_users table; batch mode rebuilds the table underneath.
    with op.batch_alter_table('audit_logs', schema=None,
                              naming_convention=FK_NAMING) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'],
                              unique=False)
        batch_op.drop_constraint('fk_audit_logs_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_audit_logs_user_id_app_users', 'app_users',
                                    ['user_id'], ['id'])

    with op.batch_alter_table('records', schema=None,
                              naming_convention=FK_NAMING) as batch_op:
        batch_op.create_index(batch_op.f('ix_records_created_by'), ['created_by'],
                              unique=False)
        batch_op.create_index(batch_op.f('ix_records_updated_by'), ['updated_by'],
                              unique=False)
        batch_op.drop_constraint('fk_records_created_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_records_updated_by_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_records_created_by_app_users', 'app_users',
                                    ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_records_updated_by_app_users', 'app_users',
                                    ['updated_by'], ['id'])

    with op.batch_alter_table('wells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pm_code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('well_class', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_wells_pm_code'), ['pm_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_wells_well_class'), ['well_class'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wells_well_class'))
        batch_op.drop_index(batch_op.f('ix_wells_pm_code'))
        batch_op.drop_column('address')
        batch_op.drop_column('well_class')
        batch_op.drop_column('pm_code')

    with op.batch_alter_table('records', schema=None,
                              naming_convention=FK_NAMING) as batch_op:
        batch_op.drop_constraint('fk_records_updated_by_app_users', type_='foreignkey')
        batch_op.drop_constraint('fk_records_created_by_app_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_records_updated_by_users', 'users',
                                    ['updated_by'], ['id'])
        batch_op.create_foreign_key('fk_records_created_by_users', 'users',
                                    ['created_by'], ['id'])
        batch_op.drop_index(batch_op.f('ix_records_updated_by'))
        batch_op.drop_index(batch_op.f('ix_records_created_by'))

    with op.batch_alter_table('audit_logs', schema=None,
                              naming_convention=FK_NAMING) as batch_op:
        batch_op.drop_constraint('fk_audit_logs_user_id_app_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_audit_logs_user_id_users', 'users',
                                    ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_login_at'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_users_username'))
        batch_op.drop_index(batch_op.f('ix_app_users_personnel_code'))
        batch_op.drop_index(batch_op.f('ix_app_users_national_id'))
        batch_op.drop_index(batch_op.f('ix_app_users_is_active'))

    op.drop_table('app_users')
    # ### end Alembic commands ###
