"""conditional field visibility

Revision ID: 5accc7790812
Revises: 850ea3df5f9f
Create Date: 2026-09-14 06:25:41.324259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5accc7790812'
down_revision = '850ea3df5f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_when', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.drop_column('visible_when')

    # ### end Alembic commands ###
